ENV["VAGRANT_EXPERIMENTAL"] = "typed_triggers"

system("
    if [ #{ARGV[0]} = 'up' ]; then
        echo 'You are doing vagrant up and can execute your script'
        tar -cvf libelektra.tar -C ../../.. .
    fi
")

Vagrant.configure("2") do |config|
    config.vm.box = "amarcireau/macos"
    config.vm.box_version = "11.3.1"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |v|
        v.check_guest_additions = false
        v.customize ["modifyvm", :id, "--cpus"  , "4"   ]
        v.customize ["modifyvm", :id, "--memory", "6144"]
    end
    config.vm.provision "shell", path: 'provision.sh', privileged: false
    config.vm.provision "file", source: "libelektra.tar", destination: "/tmp/libelektra.tar"
    config.vm.provision "shell", inline: "mkdir /Users/vagrant/elektra"
    config.vm.provision "shell", inline: "tar -C /Users/vagrant/elektra/ -xvf /tmp/libelektra.tar"
    config.trigger.after :"VagrantPlugins::ProviderVirtualBox::Action::Import", type: :action do |t|
        t.ruby do |env, machine|
            FileUtils.cp(
                machine.box.directory.join("include").join("macOS.nvram").to_s,
                machine.provider.driver.execute_command(["showvminfo", machine.id, "--machinereadable"]).
                    split(/\n/).
                    map {|line| line.partition(/=/)}.
                    select {|partition| partition.first == "BIOS NVRAM File"}.
                    last.
                    last[1..-2]
            )
        end
    end
end